package com.silverpants.instantaneous.misc

const val AUTH_OTP_TIMEOUT = 60L

const val CHAT_MAX_DISPLAY_MESSAGES = 50L

val FALLBACK_DPS = arrayOf(
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/01.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/02.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/03.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/04.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/05.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/06.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/07.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/dark/08.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/01.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/02.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/03.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/04.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/05.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/06.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/07.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/orange/08.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/01.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/02.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/03.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/04.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/05.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/06.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/07.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/purple/08.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/01.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/02.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/03.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/04.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/05.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/06.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/07.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/teal/08.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/01.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/02.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/03.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/04.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/05.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/06.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/07.png",
    "https://storage.googleapis.com/instantaneous-e673e.appspot.com/fallbacks/yellow/08.png")